// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjcluxfejamiiqddxfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuamNsdXhmZWphbWlpcWRkeGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNzYzNDUsImV4cCI6MjA2Mzc1MjM0NX0.Tu8bQ9tkAj4dqXV43CvGMcCWCoIMJCadKVpE_QAS2iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);