// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghuieymlmxycydzzsmmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdodWlleW1sbXh5Y3lkenpzbW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDQzNDEsImV4cCI6MjA2NDQyMDM0MX0.3TYU1M-4lk_bZjnOQWf-EEPyyxlHJ6w8MsVW-3nkl60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);